# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transfer_Attr.ui'
#
# Created: Mon May 18 00:00:40 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(428, 610)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.attr_List_Layout = QtGui.QVBoxLayout()
        self.attr_List_Layout.setObjectName("attr_List_Layout")
        self.attr_listView = QtGui.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.attr_listView.setFont(font)
        self.attr_listView.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.attr_listView.setObjectName("attr_listView")
        self.attr_List_Layout.addWidget(self.attr_listView)
        self.verticalLayout.addLayout(self.attr_List_Layout)
        self.move_But_Layout = QtGui.QHBoxLayout()
        self.move_But_Layout.setObjectName("move_But_Layout")
        self.move_up_But = QtGui.QPushButton(self.centralwidget)
        self.move_up_But.setAutoDefault(False)
        self.move_up_But.setDefault(True)
        self.move_up_But.setFlat(False)
        self.move_up_But.setObjectName("move_up_But")
        self.move_But_Layout.addWidget(self.move_up_But)
        self.move_Down_But = QtGui.QPushButton(self.centralwidget)
        self.move_Down_But.setDefault(True)
        self.move_Down_But.setObjectName("move_Down_But")
        self.move_But_Layout.addWidget(self.move_Down_But)
        self.verticalLayout.addLayout(self.move_But_Layout)
        self.sel_obj_Det_Layout = QtGui.QVBoxLayout()
        self.sel_obj_Det_Layout.setObjectName("sel_obj_Det_Layout")
        self.object_name = QtGui.QLabel(self.centralwidget)
        self.object_name.setEnabled(False)
        self.object_name.setObjectName("object_name")
        self.sel_obj_Det_Layout.addWidget(self.object_name)
        self.keyable_check_Box = QtGui.QCheckBox(self.centralwidget)
        self.keyable_check_Box.setObjectName("keyable_check_Box")
        self.sel_obj_Det_Layout.addWidget(self.keyable_check_Box)
        self.verticalLayout.addLayout(self.sel_obj_Det_Layout)
        self.data_typebut_Layout = QtGui.QHBoxLayout()
        self.data_typebut_Layout.setObjectName("data_typebut_Layout")
        self.lock_But = QtGui.QPushButton(self.centralwidget)
        self.lock_But.setObjectName("lock_But")
        self.data_typebut_Layout.addWidget(self.lock_But)
        self.hide_But = QtGui.QPushButton(self.centralwidget)
        self.hide_But.setObjectName("hide_But")
        self.data_typebut_Layout.addWidget(self.hide_But)
        self.verticalLayout.addLayout(self.data_typebut_Layout)
        self.data_typebut_Layout_2 = QtGui.QHBoxLayout()
        self.data_typebut_Layout_2.setObjectName("data_typebut_Layout_2")
        self.keyable_But = QtGui.QPushButton(self.centralwidget)
        self.keyable_But.setObjectName("keyable_But")
        self.data_typebut_Layout_2.addWidget(self.keyable_But)
        self.delete_But = QtGui.QPushButton(self.centralwidget)
        self.delete_But.setObjectName("delete_But")
        self.data_typebut_Layout_2.addWidget(self.delete_But)
        self.verticalLayout.addLayout(self.data_typebut_Layout_2)
        self.transfer_Attr_Lay = QtGui.QVBoxLayout()
        self.transfer_Attr_Lay.setObjectName("transfer_Attr_Lay")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.transfer_Attr_Lay.addWidget(self.label)
        self.delete_Source_Check = QtGui.QCheckBox(self.centralwidget)
        self.delete_Source_Check.setObjectName("delete_Source_Check")
        self.transfer_Attr_Lay.addWidget(self.delete_Source_Check)
        self.transfer_connections_Check = QtGui.QCheckBox(self.centralwidget)
        self.transfer_connections_Check.setObjectName("transfer_connections_Check")
        self.transfer_Attr_Lay.addWidget(self.transfer_connections_Check)
        self.verticalLayout.addLayout(self.transfer_Attr_Lay)
        self.transfer_But_Layout = QtGui.QHBoxLayout()
        self.transfer_But_Layout.setObjectName("transfer_But_Layout")
        self.reload_But = QtGui.QPushButton(self.centralwidget)
        self.reload_But.setObjectName("reload_But")
        self.transfer_But_Layout.addWidget(self.reload_But)
        self.transfer_But = QtGui.QPushButton(self.centralwidget)
        self.transfer_But.setObjectName("transfer_But")
        self.transfer_But_Layout.addWidget(self.transfer_But)
        self.verticalLayout.addLayout(self.transfer_But_Layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 428, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Transfer Attributes", None, QtGui.QApplication.UnicodeUTF8))
        self.move_up_But.setText(QtGui.QApplication.translate("MainWindow", "MOVE UP", None, QtGui.QApplication.UnicodeUTF8))
        self.move_Down_But.setText(QtGui.QApplication.translate("MainWindow", "MOVE DOWN", None, QtGui.QApplication.UnicodeUTF8))
        self.object_name.setText(QtGui.QApplication.translate("MainWindow", "select Object", None, QtGui.QApplication.UnicodeUTF8))
        self.keyable_check_Box.setText(QtGui.QApplication.translate("MainWindow", "list keyable only", None, QtGui.QApplication.UnicodeUTF8))
        self.lock_But.setText(QtGui.QApplication.translate("MainWindow", "LOCK", None, QtGui.QApplication.UnicodeUTF8))
        self.hide_But.setText(QtGui.QApplication.translate("MainWindow", "HIDE", None, QtGui.QApplication.UnicodeUTF8))
        self.keyable_But.setText(QtGui.QApplication.translate("MainWindow", "KEYABLE", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_But.setText(QtGui.QApplication.translate("MainWindow", "DELETE", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "TRANSFER ATTR :", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_Source_Check.setText(QtGui.QApplication.translate("MainWindow", "delete source attr", None, QtGui.QApplication.UnicodeUTF8))
        self.transfer_connections_Check.setText(QtGui.QApplication.translate("MainWindow", "transfer connections", None, QtGui.QApplication.UnicodeUTF8))
        self.reload_But.setText(QtGui.QApplication.translate("MainWindow", "RELOAD", None, QtGui.QApplication.UnicodeUTF8))
        self.transfer_But.setText(QtGui.QApplication.translate("MainWindow", "TRANSFER ATTR", None, QtGui.QApplication.UnicodeUTF8))

