from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(428, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.attr_List_Layout = QtWidgets.QVBoxLayout()
        self.attr_List_Layout.setObjectName("attr_List_Layout")
        self.attr_listView = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.attr_listView.setFont(font)
        self.attr_listView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.attr_listView.setObjectName("attr_listView")
        self.attr_List_Layout.addWidget(self.attr_listView)
        self.verticalLayout.addLayout(self.attr_List_Layout)
        self.move_But_Layout = QtWidgets.QHBoxLayout()
        self.move_But_Layout.setObjectName("move_But_Layout")
        self.move_up_But = QtWidgets.QPushButton(self.centralwidget)
        self.move_up_But.setAutoDefault(False)
        self.move_up_But.setDefault(True)
        self.move_up_But.setFlat(False)
        self.move_up_But.setObjectName("move_up_But")
        self.move_But_Layout.addWidget(self.move_up_But)
        self.move_Down_But = QtWidgets.QPushButton(self.centralwidget)
        self.move_Down_But.setDefault(True)
        self.move_Down_But.setObjectName("move_Down_But")
        self.move_But_Layout.addWidget(self.move_Down_But)
        self.verticalLayout.addLayout(self.move_But_Layout)
        self.sel_obj_Det_Layout = QtWidgets.QVBoxLayout()
        self.sel_obj_Det_Layout.setObjectName("sel_obj_Det_Layout")
        self.object_name = QtWidgets.QLabel(self.centralwidget)
        self.object_name.setEnabled(False)
        self.object_name.setObjectName("object_name")
        self.sel_obj_Det_Layout.addWidget(self.object_name)
        self.keyable_check_Box = QtWidgets.QCheckBox(self.centralwidget)
        self.keyable_check_Box.setObjectName("keyable_check_Box")
        self.sel_obj_Det_Layout.addWidget(self.keyable_check_Box)
        self.verticalLayout.addLayout(self.sel_obj_Det_Layout)
        self.data_typebut_Layout = QtWidgets.QHBoxLayout()
        self.data_typebut_Layout.setObjectName("data_typebut_Layout")
        self.lock_But = QtWidgets.QPushButton(self.centralwidget)
        self.lock_But.setObjectName("lock_But")
        self.data_typebut_Layout.addWidget(self.lock_But)
        self.hide_But = QtWidgets.QPushButton(self.centralwidget)
        self.hide_But.setObjectName("hide_But")
        self.data_typebut_Layout.addWidget(self.hide_But)
        self.verticalLayout.addLayout(self.data_typebut_Layout)
        self.data_typebut_Layout_2 = QtWidgets.QHBoxLayout()
        self.data_typebut_Layout_2.setObjectName("data_typebut_Layout_2")
        self.keyable_But = QtWidgets.QPushButton(self.centralwidget)
        self.keyable_But.setObjectName("keyable_But")
        self.data_typebut_Layout_2.addWidget(self.keyable_But)
        self.delete_But = QtWidgets.QPushButton(self.centralwidget)
        self.delete_But.setObjectName("delete_But")
        self.data_typebut_Layout_2.addWidget(self.delete_But)
        self.verticalLayout.addLayout(self.data_typebut_Layout_2)
        self.transfer_Attr_Lay = QtWidgets.QVBoxLayout()
        self.transfer_Attr_Lay.setObjectName("transfer_Attr_Lay")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.transfer_Attr_Lay.addWidget(self.label)
        self.delete_Source_Check = QtWidgets.QCheckBox(self.centralwidget)
        self.delete_Source_Check.setObjectName("delete_Source_Check")
        self.transfer_Attr_Lay.addWidget(self.delete_Source_Check)
        self.transfer_connections_Check = QtWidgets.QCheckBox(self.centralwidget)
        self.transfer_connections_Check.setObjectName("transfer_connections_Check")
        self.transfer_Attr_Lay.addWidget(self.transfer_connections_Check)
        self.verticalLayout.addLayout(self.transfer_Attr_Lay)
        self.transfer_But_Layout = QtWidgets.QHBoxLayout()
        self.transfer_But_Layout.setObjectName("transfer_But_Layout")
        self.reload_But = QtWidgets.QPushButton(self.centralwidget)
        self.reload_But.setObjectName("reload_But")
        self.transfer_But_Layout.addWidget(self.reload_But)
        self.transfer_But = QtWidgets.QPushButton(self.centralwidget)
        self.transfer_But.setObjectName("transfer_But")
        self.transfer_But_Layout.addWidget(self.transfer_But)
        self.verticalLayout.addLayout(self.transfer_But_Layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 428, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Transfer Attributes", None, -1))
        self.move_up_But.setText(QtWidgets.QApplication.translate("MainWindow", "MOVE UP", None, -1))
        self.move_Down_But.setText(QtWidgets.QApplication.translate("MainWindow", "MOVE DOWN", None, -1))
        self.object_name.setText(QtWidgets.QApplication.translate("MainWindow", "select Object", None, -1))
        self.keyable_check_Box.setText(QtWidgets.QApplication.translate("MainWindow", "list keyable only", None, -1))
        self.lock_But.setText(QtWidgets.QApplication.translate("MainWindow", "LOCK", None, -1))
        self.hide_But.setText(QtWidgets.QApplication.translate("MainWindow", "HIDE", None, -1))
        self.keyable_But.setText(QtWidgets.QApplication.translate("MainWindow", "KEYABLE", None, -1))
        self.delete_But.setText(QtWidgets.QApplication.translate("MainWindow", "DELETE", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "TRANSFER ATTR :", None, -1))
        self.delete_Source_Check.setText(QtWidgets.QApplication.translate("MainWindow", "delete source attr", None, -1))
        self.transfer_connections_Check.setText(QtWidgets.QApplication.translate("MainWindow", "transfer connections", None, -1))
        self.reload_But.setText(QtWidgets.QApplication.translate("MainWindow", "RELOAD", None, -1))
        self.transfer_But.setText(QtWidgets.QApplication.translate("MainWindow", "TRANSFER ATTR", None, -1))

